name: Node.js CI/CD API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Front-End Steps (if applicable)
    - name: Install Front-End Dependencies
      working-directory: ./frontend  # Path to your front-end code
      run: npm ci

    # Back-End Steps
    - name: Install Back-End Dependencies
      working-directory: ./backend  # Path to your back-end code
      run: npm ci

    - name: Restart Back-End Server
      working-directory: ./backend
      run: pm2 restart Backend  # Replace `Backend` with your PM2 process name



    
